name: Main

on:
- push
- pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'
        bundler-cache: true
    - uses: shogo82148/actions-setup-perl@v1
      with:
        install-modules-with: cpanm
    - name: Test
      run: bundle exec rake test
